export default {
  Lime: 'lime',
  Blue: 'blue',
  LightBlue: 'lightblue',
  LightGreen: 'lightgreen',
  DarkBlue: 'darkblue',
  White: 'white',
  Yellow: 'yellow',
  Purple: '#aa00ff',
  Red: 'red',
  CustomBlue: '#304ffe',
  CustomGreen: '#06623b',
  CustomLightGreen: '#ccff90',
  LightGreen_A5: '#ccff90b3',
  CustomWhite: '#fafafa',
  Gray: 'gray',
  LightGray: 'lightgray',
  CustomLightBlue: '#e0f2f1',
  Green: 'green',
  Orange: 'orange',
};
